# Generated by Django 3.1.1 on 2020-09-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='color',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
